### ISSUE TITLE
你好,请问仿DNF武器系统是怎么用啊?

### ISSUE THREAD

**Issue by Rousong** [WickhamWei/WickhamsPlugin#1]
你好,感谢制作的插件!我有几个问题
1.请问仿DNF武器系统是怎么用啊?
2.主城区域的坐标可以改么 ?>>
3.公告的颜色应该怎么修改啊?
谢谢!!

**Comment by WickhamWei** [comment]
谢谢你的提问
1.RPG系统暂未完成，建议关闭。不过也应该没有BUG，可以尝试。
三个木棍竖着摆合成基础木柄，八个铁粒合成基础铁碎片。
铁碎片和木柄摆成剑的形状可以合成“破损的铁剑”
破损的铁剑可以升级，满耐久放在合成表中心，在上方左方右方放基础铁碎片，下方放基础木柄。
可以合成“生锈的铁剑”，以此类推，攻击力和攻击速度以此类推。
2.如果/setspawn不管用，可能是我忘了写，几天内更新。
3.正在研究合适的解决方案，目前只想到正则表达式。

**Comment by WickhamWei** [comment]
2和3已经解决，请更新最新版本，谢谢！
